### ISSUE TITLE
Zammad Betreff

### ISSUE THREAD

**Issue by Matzeroth** [corpatch/daily-business#4]
Sascha, kannst du mal rausbekommen, wir man bei einer Mail den Betreff ändert? Oder muss ich dafür immer ein neues Ticket aufmachen? Die Mails kommen von app@CP und müssen dann an den Benutzer.

https://support.corpatch.com/#ticket/zoom/369

Ergebnis ist dieser  Betreff... unschön...

<img width="605" alt="image" src="https://github.com/corpatch/daily-business/assets/64593786/b699d9a2-755a-4415-986b-9d1a90514926">

**Comment by Sascha-Herrmann** [comment]
Der Betreff der E-Mail ist immer die Ticketbezeichnung. Die Bezeichnung wird mit dem Betreff der E-Mail an den Support geschickt. Ich glaube in der E-Mail wird aber kein Betreff gesetzt, deshalb ist ist das ein "-". 

Bsp: 
![image](https://github.com/corpatch/daily-business/assets/151969962/d4d8bb06-2287-40c4-a0e1-14ce1cfd4661)

Entweder ich schaue, wie man der automatischen E-Mail, die das Ticket erstellt einen Betreff hinzufügt, oder man vergibt dem Ticket einen neuen Namen. Dann ist der Betreff der Email "Ticketbezeichnung [Ticket#12335]"

![image](https://github.com/corpatch/daily-business/assets/151969962/44667af3-ed2b-4de4-98b5-7ada127bfee4)


![image](https://github.com/corpatch/daily-business/assets/151969962/d0794186-3bbb-4759-a304-b3b64eb6b478)

**Comment by Matzeroth** [comment]
Oder wir machen daraus immer ein neues Ticket? Wäre vielleicht besser? Was meinst du?

**Comment by Sascha-Herrmann** [comment]
Also die E-Mail erstellt automatisch ein Ticket?, Dann werden die Infos (Dauer, Wer, Wann) nochmal in ein zusätzliches Ticket geschrieben? 

Ich denke, dass wenn man ein neues Ticket erstellt, dann hat man das "Problem" zweimal aufgeführt. 

Was wären die Vorteile von einem neuem Ticket?

**Comment by Matzeroth** [comment]
Nur dass der Benutzer richtig zugewiesen ist… hast schon recht. Lassen wir bei einem. Aber den Betreff müssen wir dann sinnvoll anpassen.

Ich hätte gerne, dass du Zugriff auf die Supportsoftware hast. Dann kannst du nur noch die weiterleiten, die wirkliche CPRs sind…

**Comment by Sascha-Herrmann** [comment]
Ich habe jetzt Zugriff auf die Support Software
